### PR TITLE
Additional properties support

### PR DESCRIPTION
**Pull request by delvedor**
Added support for `additionalProperties`.
See discussion in #5.

*Ps: I took the occasion to add a table of contents to the docs.*

### CODE REVIEW

**Comment by mcollina** [comment]
We should add a case for `additionalProperties: true` and  `additionalProperties: false`. If `additionalProperties: true` is passed, we use fast-safe-stringify to JSONify them (to avoid circular references).

**Comment by delvedor** [comment]
In case of `additionalProperties: false` all the values that are not present in `properties`/`patternProperties` are ignored.

Regarding `additionalProperties: true`, I never see in the json docs this case, only `false` or `object`. That's why I wrote [this](https://github.com/mcollina/fast-json-stringify/blob/0d4d02d0c11b9fceefe9931378d84da727ef0b3b/index.js#L254-L256).

**Comment by mcollina** [comment]
Look at this: https://spacetelescope.github.io/understanding-json-schema/reference/object.html.

> The additionalProperties keyword is used to control the handling of extra stuff, that is, properties whose names are not listed in the properties keyword. By default any additional properties are allowed.

I think we should "bend the rule here", and support `additionalProperties`  as being false by default. If someone wants to add random properties, I think we should support `additionalProperties: true`.

**Comment by delvedor** [comment]
For me is ok support `additionalProperties: true`, but how?
You say to use `fast-safe-stringify`, but we can't use require in the generated code.
I saw the source code of `fast-safe-stringify` and it's composed by three different functions and it's exposing only one of them, so I can't `fast-safe-stringify.toString()` as we do with the other functions.

Ideas?

**Comment by mcollina** [comment]
You can pass it in as an argument of https://github.com/mcollina/fast-json-stringify/blob/master/index.js#L55.

**Comment by delvedor** [comment]
If this implementation is ok for you I'll update the docs to describe this behaviour :)

**Comment by mcollina** [comment]
The implementation is ok.

**Comment by mcollina** [comment]
Does this slows down benchmarks? I don't think so, but please check.

Anyway, LGTM.

**Comment by delvedor** [comment]
I'll add more benchmarks in the future.
In the meantime I merge this :P

**Pull request merged**
